# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://robertorosmaninho.github.io/
baseurl: /homepage/
title: Roberto Rosmaninho
author: Roberto Rosmaninho
description: Personal blog and preject resumes
avatar: profile.jpeg
email: robertogrosmaninho@gmail.com
github: robertorosmaninho # username
twitter: rrosmaninho1
linkedin: robertorosmaninho
stackoverflow: users/10764683/roberto-rosmaninho  #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
